GET http://localhost:5291/games/2


###
POST http://localhost:5291/games
Content-Type: application/json

{
    "Name": "",
    "Genre": "Action-adventure",    
    "Price": 59.99,
    "ReleaseDate": "2017-03-03"
}

###
PUT http://localhost:5291/games/2
Content-Type: application/json

{
    "name": "Asphalt 9: Legends",
    "genre": "Racing",      
    "price": 19.99,
    "releaseDate": "2018-07-25" 
}